using System.Runtime.InteropServices;
using Unity.Mathematics;

namespace Box3D
{
    /// <summary>Burst-callable native entry points. Two kinds live here:
    ///
    /// <para>1. Hand-written redeclarations of C API entry points with primitive-only signatures.
    /// Burst cannot P/Invoke functions that pass or return structs by value (error BC1064), which
    /// rules out most of the generated bindings — box3d passes its id structs by value. For entry
    /// points whose every struct argument fits in a register, an ABI-identical primitive
    /// redeclaration sidesteps that: b3WorldId is 4 bytes ({u16,u16}), passed exactly like a
    /// uint32 on every register-based 64-bit ABI we ship (Windows x64, System V x64, AArch64);
    /// b3BodyId is 8 bytes, passed like a uint64. Reinterpret the id's memory
    /// (<c>*(uint*)&amp;id</c> — NOT <c>ToUInt32()</c>, which packs a different byte order).</para>
    ///
    /// <para>2. The b3u_* glue exports (Box3D.Native~/glue/box3d_unity_glue.c, compiled into the
    /// native library): pointer-based wrappers for entry points whose signatures pass vectors,
    /// filters or multi-word results by value — those can never be redeclared portably in C#
    /// (per-ABI sret and HFA conventions). Requires natives built with glue version ≥ 1;
    /// <see cref="World.Create"/> probes <see cref="b3u_GlueVersion"/> and logs a clear error on
    /// stale binaries.</para>
    ///
    /// <para>None of this is valid on WebGL: the wasm C ABI passes multi-field structs indirectly
    /// and Unity ECS/Burst don't target WebGL — call sites keep the generated by-value
    /// declarations there via <c>#if UNITY_WEBGL</c>.</para></summary>
    internal static unsafe class BurstBindings
    {
        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, EntryPoint = "b3World_Step", ExactSpelling = true)]
        public static extern void b3World_Step(uint worldId, float timeStep, int subStepCount);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int b3u_GlueVersion();

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_World_GetBodyEvents(uint worldId, void** moveEvents, int* moveCount);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_World_GetSensorEvents(uint worldId,
            void** beginEvents, int* beginCount, void** endEvents, int* endCount);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_World_GetContactEvents(uint worldId,
            void** beginEvents, int* beginCount, void** endEvents, int* endCount, void** hitEvents, int* hitCount);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_World_GetJointEvents(uint worldId, void** jointEvents, int* count);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_World_CastRayClosest(uint worldId,
            B3Pos* origin, float3* translation, QueryFilter* filter, RayResult* result);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int b3u_World_CastRay(uint worldId,
            B3Pos* origin, float3* translation, QueryFilter* filter, RayHit* hits, int capacity, b3TreeStats* stats);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int b3u_World_OverlapAABB(uint worldId,
            B3Aabb* aabb, QueryFilter* filter, ShapeId* results, int capacity, b3TreeStats* stats);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_Body_GetTransform(ulong bodyId, B3WorldTransform* result);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_Body_SetTransform(ulong bodyId, B3Pos* position, quaternion* rotation);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_Body_GetLinearVelocity(ulong bodyId, float3* result);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_Body_SetLinearVelocity(ulong bodyId, float3* velocity);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_Body_GetAngularVelocity(ulong bodyId, float3* result);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_Body_SetAngularVelocity(ulong bodyId, float3* velocity);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_Body_ApplyLinearImpulse(ulong bodyId, float3* impulse, B3Pos* point, NativeBool wake);

        [DllImport(Box3DLibrary.Name, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void b3u_Body_ApplyLinearImpulseToCenter(ulong bodyId, float3* impulse, NativeBool wake);
    }
}
